### ISSUE TITLE
Searchex Roadmap

### ISSUE THREAD

**Issue by agustif** [elixir-search/searchex#8]
hi @andyl thanks for the code, it's been helpful to look at!

I was wondering seeing the roadmap, if you're still interested on that, I'm asking because I found your repo while I was thinking to do a kinda similar thing (Just hadn't worried about using elixir for search perse)

I want to build a website to aggregate all info possible on elixir, be it docs, blogs, videos, courses, books, etc..

Is that your end goal to? Do you want help on your project? I see it's been stale for a few months, and wonder what are your thoughts on this.

I was just gonna use Phoenix and see what sticks, maybe use Postgres basic search for now. Or elasticSearch if something external was needed (though I wouldn't expect massive traffic )

**Comment by andyl** [comment]
Hi !  I've been busy the past couple months with other projects.  I intend to finish Searchex and think it's possible to build something great.  I would love to work with a collaborator.

There are two reasons why IMO an elixir-based search engine would be useful.  1) for something faster/easier to manage than elastic search and 2) I think we can do something amazing with streaming data.

Having said all that: let me know how you would like to participate.  Also I would be interested in contributing to your Phoenix project.

**Comment by agustif** [comment]
Hi! Count me on, The project looks interesting and overlapping with what I had in mind.

If you think that'd be fine, we could both work on advancing on your Roadmap (I want to have search on my Ecto/Phoenix App, what better way than using searchex, I also planned to scrap/be able to search docs and such as you outlined...

Anyways, What I had in mind, was kind of a all things elixir aggregator which was capable to relate stuff, I also was thinking of it kinda of like a place for any elixir user to both browse and save stuff (links, snippets, etc) and be able to set it up to public or private)

I am an elixir fan, have like 5 books on it, I hunt github daily for elixir projects, etc, I want to use all that effort on my end in order to put an aggregator which can be maanged with a community like myself. I think elixir would be a good fit for this, people is really nice!

**Comment by agustif** [comment]
Oh, just as a note, I also kinda had the inspiration from https://kite.com/

I mean, if we got smart enough about elixir we could provide this kinda -copilot- which does much more than give you docs, being able to link to examples from blogposts, youtube, etc would be also valuable.

Anyways, elixir is not in kite.com roadmaps, so let's build our own open source version of it

**Comment by andyl** [comment]
Great!  How about we have a kickoff meeting sometime next week?  Proposed agenda (60-90 mins):
- history and rationale for searchex
- current state of the project, roadmap and immediate next steps
- personal motivations and goals
- phoenix demonstration project
- team communication style, code management practices, time expectations
- etc.

Proposed comms SW for the meetup: tmate for screen sharing, skype for voice, vimdeck for presentations, vim for note taking 

To prepare we should each 1) read, install and run the code 2) install/test the comms SW.

How does that sound?

Re: kite - the idea of a copilot is nice inspiration.  I imagine the co-pilot idea could apply to other domains.  

Generally I'm looking for 1) technical learning, 2) making friends, 3) solving personal/technical issues, 4) commercial potential, 5) stoke factor.
